import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Shivam',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Toothpaste',
        logo: 'https://res.cloudinary.com/dtrx9n8hl/image/upload/v1612787468/e-com/3321_wecvqs.jpg',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike casual shoes',
      category: 'Shoes',
      image: 'https://res.cloudinary.com/dtrx9n8hl/image/upload/v1608838107/e-com/18104213_cynq2t.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit boots',
      category: 'Shoes',
      image: 'https://res.cloudinary.com/dtrx9n8hl/image/upload/v1608838107/e-com/18104213_cynq2t.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'sneakers',
      category: 'Shoes',
      image: 'https://res.cloudinary.com/dtrx9n8hl/image/upload/v1608838107/e-com/18104213_cynq2t.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'lawng',
      category: 'tootpaste',
      image: 'https://res.cloudinary.com/dtrx9n8hl/image/upload/v1608838107/e-com/18104213_cynq2t.jpg',
      price: 78,
      countInStock: 15,
      brand: 'colgate',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'pudina',
      category: 'tootpaste',
      image: 'https://res.cloudinary.com/dtrx9n8hl/image/upload/v1608838107/e-com/18104213_cynq2t.jpg',
      price: 65,
      countInStock: 5,
      brand: 'colgate',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'lemon',
      category: 'toothpaste',
      image: 'https://res.cloudinary.com/dtrx9n8hl/image/upload/v1608838107/e-com/18104213_cynq2t.jpg',
      price: 139,
      countInStock: 12,
      brand: 'colgate',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'mint',
      category: 'tootpaste',
      image: 'https://res.cloudinary.com/dtrx9n8hl/image/upload/v1608838107/e-com/18104213_cynq2t.jpg',
      price: 139,
      countInStock: 12,
      brand: 'colgate',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    }
  ],
};
export default data;
